config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  resources :orders, :path => "commande"

  resources :items_in_carts, only: [:create, :destroy]
  
  devise_for :users, :path => "utilisateur"
  
  resources :items, :path => "chat" do
    resources :images, only: [:create]
    get ":id" => :show, as: "chatons"
  end
  
  resources :users, :path => "utilisateur", except: [:index]  do
    resources :carts, :path => "panier"
  end

end

app/models/items_in_cart.rb
class ItemsInCart < ApplicationRecord
  belongs_to :item, optional: true
  belongs_to :cart, optional: true
  belongs_to :order, optional: true
  
end

app/controllers/items_in_carts_controller.rb
class ItemsInCartsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  before_action :set_items_in_cart, only: %i[ show edit update destroy ]

  # GET /items_in_carts or /items_in_carts.json
  def index
    @items_in_carts = ItemsInCart.all
  end

  # GET /items_in_carts/1 or /items_in_carts/1.json
  def show
    
  end

  # GET /items_in_carts/new
  def new
    @items_in_cart = ItemsInCart.new
  end

  # GET /items_in_carts/1/edit
  def edit
  end

  # POST /items_in_carts or /items_in_carts.json
  def create
    chosen_product = Item.find(params[:item_id])
    current_cart = @current_cart

    @items_in_cart = ItemsInCart.new
    @items_in_cart.cart = current_cart
    @items_in_cart.item = chosen_product

  # Save and redirect to cart show path

    respond_to do |format|
      if @items_in_cart.save
        format.html { redirect_to root_path, notice: "Votre produit a bien été ajouté." }# ajouter flash sur la bonne page 
        format.json { render :show, status: :created, location: @items_in_cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @items_in_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items_in_carts/1 or /items_in_carts/1.json
  def update
    respond_to do |format|
      if @items_in_cart.update(items_in_cart_params)
        format.html { redirect_to @items_in_cart, notice: "Votre ajout a été modifié." }
        format.json { render :show, status: :ok, location: @items_in_cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @items_in_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items_in_carts/1 or /items_in_carts/1.json
  def destroy
    @items_in_cart.destroy
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: "votre article a bien été supprimé" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_items_in_cart
      @items_in_cart = ItemsInCart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def items_in_cart_params
      params.fetch(:items_in_cart, {})
    end
end

app/helpers/items_in_carts_helper.rb
module ItemsInCartsHelper
end

app/views/items_in_carts/_form.html.erb
<%= form_with(model: items_in_cart, local: true) do |form| %>
  <% if items_in_cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(items_in_cart.errors.count, "error") %> prohibited this items_in_cart from being saved:</h2>

      <ul>
      <% items_in_cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items_in_carts/edit.html.erb
<h1>Editing Items In Cart</h1>

<%= render 'form', items_in_cart: @items_in_cart %>

<%= link_to 'Show', @items_in_cart %> |
<%= link_to 'Back', items_in_carts_path %>

app/views/items_in_carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items In Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items_in_carts.each do |items_in_cart| %>
      <tr>
        <td><%= link_to 'Show', items_in_cart %></td>
        <td><%= link_to 'Edit', edit_items_in_cart_path(items_in_cart) %></td>
        <td><%= link_to 'Destroy', items_in_cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Items In Cart', new_items_in_cart_path %>

app/views/items_in_carts/new.html.erb
<h1>New Items In Cart</h1>

<%= render 'form', items_in_cart: @items_in_cart %>

<%= link_to 'Back', items_in_carts_path %>

app/views/items_in_carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_items_in_cart_path(@items_in_cart) %> |
<%= link_to 'Back', items_in_carts_path %>