config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  resources :orders, :path => "commande"

  resources :items_in_carts, only: [:create, :destroy]
  
  devise_for :users, :path => "utilisateur"
  
  resources :items, :path => "chat" do
    resources :images, only: [:create]
    get ":id" => :show, as: "chatons"
  end
  
  resources :users, :path => "utilisateur", except: [:index]  do
    resources :carts, :path => "panier"
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
  
  has_many :items, through: :items_in_carts
  belongs_to :user, optional: true
  has_many :items_in_cart, dependent: :destroy

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]
  before_action :cart_authorized?
  # GET /carts or /carts.json
  def index
    @carts = Cart.all
    @user_cart = Cart.where(user_id: user_params)
    @user_id = current_user.id
    @items_in_cart = ItemsInCart.where(cart_id: @user_cart)
    @cart_id = @user_cart.last.id
    @sum = @sum
  
  end

  # GET /carts/1 or /carts/1.json
  def show
    
  end

  # GET /carts/new
  def new
    @cart = Cart.new
    @user = User.find(params[id: user_id])
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  # def create
  #   @cart = Cart.new(cart_params)

  #   respond_to do |format|
  #     if @cart.save
  #       format.html { redirect_to @cart, notice: "Cart was successfully created." }
  #       format.json { render :show, status: :created, location: @cart }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @cart.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    def user_params
      params.require(:user_id)
    end

    def cart_authorized?
      @user_cart = Cart.where(user_id: user_params)
      @cart_id = @user_cart.last.id
      if @cart_id == @current_cart.id
        return true
        # if @cart_id == nil
        #   return false
        # else
        #   flash[:alert] = "veuillez vous connecter!"
        #   redirect_to new_user_registration_path
        # end
      else
        flash[:alert] = "Ce n'est pas votre panier!"
        redirect_to root_path
        return false
      end 
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/_show.html.erb
<div class="container-fluid mt-5" style="height: 90vh">
  <section id="shoppingcart">
    <div class="card">
      <div class="row">
        <div class="col-md-8 cart content-center ">
          <div class="row border-top border-bottom ">
            <div class="row main align-items-center">
              <% @sum = 0 %>
              <% @items_in_cart.each do |element| %>
                <div class="col-2">
                  <% if element.item.image.attached? %>
                    <%= image_tag element.item.image %>
                  <% end %>
                </div>
                <div class="col-7">
                  <p class="row"><%=element.item.title%></p>
                </div>
                <div class="col-2">
                  <p> <%= element.item.price%> € </p>
                </div>
              </div>
            </div>
            <div class="col-1">
              <div class="col-1">
                <div class="col-1">
                  <%= link_to 'x', items_in_cart_path(element.id),  method: :delete %>
                </div>
                <% @sum = @sum + element.item.price %>
              <%end%>
            </div>
          </div>
        </div>
        <div class="col-md-4 summary">
          <div class="col align-self-center text-center text-muted">
            <div class="col align-self-center text-center text-muted">
              <div class="col align-self-center text-center text-muted">
                <div class="col">
                  <% if @items_in_cart.count == 0%>
                    <h4><b>Votre Panier est vide...</b></h4>
                  <%else%>
                    <h4><b>Panier</b></h4>
                  <%end%>
                </div>
              </div>
              <hr>
              <div class="row" style="border-top: rgba(0,0,0,.1); padding: 2vh 0;">
                <% if @items_in_cart.count != 0%>
                  <% if @items_in_cart.count != 0%>
                    <% if @items_in_cart.count != 0%>
                      <div class="col">
                        <p>Nombre d'articles </p>
                        <p> Prix total </p>
                      </div>
                      <div class="col text-right">
                        <p><%= @items_in_cart.count%> </p>
                        <p> <%= @sum %> € </p>
                      </div>
                    <% end %>
                  </div>
                  <hr>
                  <% if @items_in_cart.count != 0 %>
                    <p><%= link_to "Commander", new_order_path(:sum => @sum), class:'btn' %></p>
                  <% else %>
                    <p><%= link_to "Trouver le chat de mes rêves", root_path, class:'btn' %></p>
                  <% end %>
                </div>
              </div>
            </div>
          </section>
        </div>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', user_carts_path %>

app/views/carts/index.html.erb
<%= render 'show' %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', user_carts_path %>

app/views/carts/show.html.erb
<section id="shoppingcart">
<p id="notice"><%= notice %></p>
  
</section>