config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  resources :orders, :path => "commande"

  resources :items_in_carts, only: [:create, :destroy]
  
  devise_for :users, :path => "utilisateur"
  
  resources :items, :path => "chat" do
    resources :images, only: [:create]
    get ":id" => :show, as: "chatons"
  end
  
  resources :users, :path => "utilisateur", except: [:index]  do
    resources :carts, :path => "panier"
  end

end

app/models/item.rb
class Item < ApplicationRecord
 
  validates :price, presence: true, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }

  validates :title, presence: true,length: {minimum: 3, maximum: 140}  #limites caractères (min/max)
  
  validates :description, presence: true, length: {minimum: 20, maximum: 1000}  #limites caractères (min/max)
  
  has_many :carts
  has_many :items_in_cart, dependent: :destroy

  has_one_attached :image

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
    @item = Item.find(params[:id])
    
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)
    @item.image.attach(params[:image])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<!DOCTYPE html>
<html lang="zxx"> 

<body>
    <!-- Categories Section Begin -->
    <section class="categories">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 p-0">
                <div class="categories__item categories__large__item set-bg">        
                    <div class="categories__text">
                        <h1>N'hésitez plus !</h1>
                        <p>Moelleux intense, tendre regard : choisissez  le chat qui vous correspond parmi notre large panel de photos ! Tous ont été capturé par nos meilleurs photographe, et ces clichés uniques ne manqueront pas de vous impressionner ! </p>
                        <br><br>
                        <a id="shop_now" href="#title">Voir nos produits</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 p-0">
                       <div class="bgcategory">
                       <div class="categories__item set-bg" >
                        
                            <div class="categories__text">
                                <h4>100% Bio</h4>
                                <p>Certifié sans produits chimiques</p>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 p-0">
                    <div class="bgcategory3">
                        <div class="categories__item set-bg">
                            <div class="categories__text">
                            
                                <h4>100% Hypoallergénique</h4>
                                <p>Sans risques d'allergies</p>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 p-0">
                        <div class="bgcategory2">
                        <div class="categories__item set-bg" data-setbg="img/categories/category-4.jpg">
                            <div class="categories__text">
                                <h4>100% Câlins</h4>
                                <p>D'une douceur incroyable</p>
                            </div>
                        </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 p-0">
                    <div class="bgcategory4">
                        <div class="categories__item set-bg" data-setbg="img/categories/category-5.jpg">
                            <div class="categories__text">
                                <h4>Surprenants</h4>
                                <p>Des individus uniques</p>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Categories Section End -->
<section id="title">
    <center><br><br>
    <h4>Nos produits</h4>
    <center>
<!-- Product Section Begin -->
<section class="product spad">
    <div class="container">
        <div class="row">
            <% @items.each do |item| %>
           <div class="col-lg-4 col-md-6 col-sm-12 mix women">
                <div class="product__item">
                    <div class="product__item__pic set-bg">
                        <% if item.image.attached? %>
                        <%= image_tag item.image, alt: 'avatar' %>
                        <% else %>
                        <p>Il n'y a pas encore d'avatar lié à ce produit</p>	
                        <% end %>
                    </div>
                    <div class="product__item__text">

                        <a> <h6> <%=link_to item.title, item_path(:id => item.id) %></h6></a>
                     
                        <div class="product__price"><%= item.price%>€</div>

                        	<p><%= button_to "Ajouter au panier ", items_in_carts_path(:item_id => item.id), {class:"btn btn--accent disable"} %></p>
                                
                        </div>
                </div>
            </div>
            <%end%>
        </div>
    </div>
</section>
<!-- Product Section End -->

</body>

</html>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<section id="showproduct" class="h-100">        




<main>
	<ul id="cards">
		<li class="card" id="card_1">
			<div class="card__content">

				<div>
					<h2><%= @item.title %></h2>
					<p><%= @item.description %></p>
          			<p><%= button_to "Ajouter au panier ", items_in_carts_path(:item_id => @item.id), {class:"btn btn--accent disable"} %></p>
					<%if current_user != nil %><br><br>
						<%if current_user.email == "admin@admin.admin"  %>
							<h3>Changer d'avatar ?</h3>
							<%= form_tag item_images_path(@item), multipart: true do %>
							<%= file_field_tag :image %>
							<%= submit_tag "mettre à jour" %>
						<%end%>
					<%end%>
		<% end %>
				</div>

				
				<% if @item.image.attached? %>
				
					<%= image_tag @item.image, alt: 'avatar' %>
				<% else %>

					<p>Il n'y a pas encore d'avatar lié à ce produit</p>	
					
				<% end %>
				
			</div>
				
			
		</li>

</section>